language: php

php:
  - 5.6
  - 7.1

before_script:
  - wget -O phpunit https://phar.phpunit.de/phpunit-5.phar
  - chmod +x phpunit
  - ./phpunit --version
  - composer install --prefer-source --no-interaction
  - composer require php-coveralls/php-coveralls

script:
  - mkdir -p build/logs
  - ./phpunit --coverage-clover build/logs/clover.xml

after_success:
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    travis_retry php vendor/bin/php-coveralls -v;
    fi

