language: php

php:
  - 5.6
  - 7.0

before_script:
  - wget -O phpunit https://phar.phpunit.de/phpunit-5.phar
  - chmod +x phpunit
  - ./phpunit --version
  - composer self-update
  - composer require php-coveralls/php-coveralls
  - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - ./phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

